name: Xinyu Hwang
bio: A Man who travels the world eating noodles
description: A Man who travels the world eating noodles
external-image: false
picture: assets/images/profiles.jpg
resume: true
resume-external: true
resume-url: 'https://google.com/?q=my+resume'
url: 'https://xinyu0601.github.io'
permalink: '/:title/'
disqus:
  shortname: mydisqus
  categories:
    - blog
    - project
github: xinyu0601
facebook: xinyu0601
twitter: andy19890601
email: 1015757334@qq.com
authors:
  johndoe:
    name: Xinyu Hwang
    bio: A Man who travels the world eating noodles
    external-image: false
    picture: assets/images/profiles.jpg
    twitter: johndoe
  jamesfoster:
    name: Xinyu Hwang
    bio: A Man who travels the world eating noodles
    external-image: false
    picture: assets/images/profiles.jpg
    twitter: jamesfoster
width: normal
projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
jekyll-mentions:
  base_url: 'https://github.com'
